CONFIG_LOG=y

CONFIG_MPIPE=y
CONFIG_MPIPE_STRUCTURE_MAX_FIELDS=5
CONFIG_MPIPE_BASE=y
CONFIG_MPIPE_BASE_APP_SRC=y
CONFIG_MPIPE_BASE_APP_SRC_BUF_SZ=9216
CONFIG_MPIPE_BASE_APP_SINK=y
CONFIG_MPIPE_AI=y
CONFIG_MPIPE_AI_CONVERT=y
CONFIG_MPIPE_AI_INFER=y
CONFIG_MPIPE_AI_DECODE=y

# The application waits for end of stream on the pipeline bus
CONFIG_ZBUS_MSG_SUBSCRIBER=y
CONFIG_ZBUS_PRIORITY_BOOST=n
CONFIG_ZBUS_LOG_LEVEL_ERR=y
